import json

s = """
AU.impression
CA.impression
DE.impression
FR.impression
UK.impression
US.impression
__consumer_offsets
all
attribution.adjust
au.app.active
au.app.event
au.app.view
au.business.event.sp
au.deal.event
au.deal.impression.statistics
au.dealmoon.event.aladdin.data.pull
au.dealmoon.event.album.change
au.dealmoon.event.api-lottery
au.dealmoon.event.at.user
au.dealmoon.event.biz-module.update
au.dealmoon.event.business.dish.tag.changed
au.dealmoon.event.cart.sync
au.dealmoon.event.comment-num.update
au.dealmoon.event.comment.create
au.dealmoon.event.comment.delete
au.dealmoon.event.comment.update
au.dealmoon.event.complimentary.voucher
au.dealmoon.event.deal.update
au.dealmoon.event.disclosure.update
au.dealmoon.event.entity.add
au.dealmoon.event.es-command
au.dealmoon.event.favorite.change
au.dealmoon.event.guide.change
au.dealmoon.event.image.preheat
au.dealmoon.event.like.change
au.dealmoon.event.local-channel-setting.update
au.dealmoon.event.local-common-setting.update
au.dealmoon.event.local.business.change
au.dealmoon.event.local.businessDish.rewardRules.flushAll
au.dealmoon.event.local.category.changed
au.dealmoon.event.local.city.changed
au.dealmoon.event.local.county.changed
au.dealmoon.event.medal.approval
au.dealmoon.event.order.change
au.dealmoon.event.order.goods.verified
au.dealmoon.event.order.paid
au.dealmoon.event.order.refund
au.dealmoon.event.post.change
au.dealmoon.event.public-test.update
au.dealmoon.event.resource.transport
au.dealmoon.event.scheduled_task
au.dealmoon.event.share.change
au.dealmoon.event.source-city-relation.change
au.dealmoon.event.sp.update
au.dealmoon.event.submitted.global
au.dealmoon.event.ugc.elite
au.dealmoon.event.user-biz-attribute.change
au.dealmoon.event.user-coupon.add
au.dealmoon.event.user-info.cancel
au.dealmoon.event.user-info.update
au.dealmoon.event.user.biz-attribute.change
au.dealmoon.event.user.follow
au.dealmoon.event.user.login
au.dealmoon.event.userdish.change
au.dealmoon.event.voucher.about.to.expire
au.dealmoon.event.voucher.auto.expire
au.dealmoon.event.voucher.gift
au.disclosure.ranking
au.editor.work
au.event.click
au.hot_deal.activity_leadin_click
au.hot_deal.clickRank_leadin_click
au.hot_deal.comment_list_view
au.hot_deal.deal_ad_click
au.hot_deal.deal_ad_request
au.hot_deal.deal_buy
au.hot_deal.deal_click
au.hot_deal.deal_comment
au.hot_deal.deal_fav
au.hot_deal.deal_leadin_click
au.hot_deal.deal_share
au.hot_deal.deal_view
au.hot_deal.exchange_leadin_click
au.hot_deal.groupBuy_leadin_click
au.hot_deal.guide_leadin_click
au.hot_deal.home_view
au.hot_deal.hotSp_leadin_click
au.hot_deal.hot_push_reading_leadin
au.hot_deal.localBiz_leadin_click
au.hot_deal.localEvent_leadin_click
au.hot_deal.local_ad_click
au.hot_deal.local_ad_request
au.hot_deal.local_leadin_click
au.hot_deal.post_leadin_click
au.hot_deal.publictest_leadin_click
au.hot_deal.read
au.hot_deal.spSubjectDetail_leadin_click
au.hot_deal.subject_leadin_click
au.impression
au.link.convertor
au.metric.event
au.metric.view
au.msg_center.msg_click
au.public_test.applied
au.public_test.behavior
au.public_test.click
au.public_test.share
au.public_test.view
au.search.deal
au.search_analysis.search_event
au.search_analysis.sp_search_event
au.sp.click
au.sp.event
au.sp.view
au.ugc.event
au.ugc.page_view
au.ugc.ugc_click
au.ugc.ugc_comment
au.ugc.ugc_fav
au.ugc.ugc_like
au.ugc.ugc_share
au.ugc.ugc_view
au.ugc_album.view
au.ugc_banner.click
au.ugc_banner.view
au.user.behavior
au.user.entity
au.user.score_log
au.user.ugc_publish
biz.ad.recomm_view
biz.app.active
biz.app.event
biz.app.view
biz.deal.event
biz.deal.impression.statistics
biz.disclosure.ranking
biz.editor.work
biz.event.click
biz.hot_deal.activity_leadin_click
biz.hot_deal.clickRank_leadin_click
biz.hot_deal.comment_list_view
biz.hot_deal.deal_ad_click
biz.hot_deal.deal_ad_request
biz.hot_deal.deal_buy
biz.hot_deal.deal_click
biz.hot_deal.deal_comment
biz.hot_deal.deal_fav
biz.hot_deal.deal_leadin_click
biz.hot_deal.deal_share
biz.hot_deal.deal_view
biz.hot_deal.disclosure_click
biz.hot_deal.disclosure_comment
biz.hot_deal.disclosure_fav
biz.hot_deal.disclosure_view
biz.hot_deal.event
biz.hot_deal.exchange_leadin_click
biz.hot_deal.groupBuy_leadin_click
biz.hot_deal.guide_leadin_click
biz.hot_deal.home_view
biz.hot_deal.hotSp_leadin_click
biz.hot_deal.hot_push_reading_leadin
biz.hot_deal.localBiz_leadin_click
biz.hot_deal.localEvent_leadin_click
biz.hot_deal.local_ad_click
biz.hot_deal.local_ad_request
biz.hot_deal.local_leadin_click
biz.hot_deal.local_view
biz.hot_deal.post_leadin_click
biz.hot_deal.publictest_leadin_click
biz.hot_deal.read
biz.hot_deal.spSubjectDetail_leadin_click
biz.hot_deal.subject_leadin_click
biz.link.convertor
biz.local.event
biz.metric.event
biz.metric.view
biz.msg_center.msg_click
biz.public-test_user_behavior.add
biz.public_test.applied
biz.public_test.click
biz.public_test.share
biz.public_test.view
biz.search.deal
biz.search_analysis.search_event
biz.search_analysis.sp_search_event
biz.sp.click
biz.sp.event
biz.sp.view
biz.ugc.event
biz.ugc.page_view
biz.ugc.ugc_click
biz.ugc.ugc_comment
biz.ugc.ugc_fav
biz.ugc.ugc_like
biz.ugc.ugc_share
biz.ugc.ugc_view
biz.ugc_album.view
biz.ugc_banner.click
biz.ugc_banner.view
biz.user.behavior
biz.user.entity
biz.user.score_log
biz.user.statistic
biz.user.ugc_publish
ca.app.active
ca.app.event
ca.app.view
ca.business.event.sp
ca.deal.event
ca.deal.impression.statistics
ca.dealmoon.event.aladdin.data.pull
ca.dealmoon.event.album.change
ca.dealmoon.event.api-lottery
ca.dealmoon.event.at.user
ca.dealmoon.event.biz-module.update
ca.dealmoon.event.business.dish.tag.changed
ca.dealmoon.event.cart.sync
ca.dealmoon.event.comment-num.update
ca.dealmoon.event.comment.create
ca.dealmoon.event.comment.delete
ca.dealmoon.event.comment.update
ca.dealmoon.event.complimentary.voucher
ca.dealmoon.event.deal.update
ca.dealmoon.event.disclosure.update
ca.dealmoon.event.entity.add
ca.dealmoon.event.es-command
ca.dealmoon.event.favorite.change
ca.dealmoon.event.guide.change
ca.dealmoon.event.image.preheat
ca.dealmoon.event.like.change
ca.dealmoon.event.local-channel-setting.update
ca.dealmoon.event.local-common-setting.update
ca.dealmoon.event.local.business.change
ca.dealmoon.event.local.businessDish.rewardRules.flushAll
ca.dealmoon.event.local.category.changed
ca.dealmoon.event.local.city.changed
ca.dealmoon.event.local.county.changed
ca.dealmoon.event.medal.approval
ca.dealmoon.event.order.change
ca.dealmoon.event.order.goods.verified
ca.dealmoon.event.order.paid
ca.dealmoon.event.order.refund
ca.dealmoon.event.post.change
ca.dealmoon.event.public-test.update
ca.dealmoon.event.resource.transport
ca.dealmoon.event.scheduled_task
ca.dealmoon.event.share.change
ca.dealmoon.event.source-city-relation.change
ca.dealmoon.event.sp.update
ca.dealmoon.event.submitted.global
ca.dealmoon.event.ugc.elite
ca.dealmoon.event.user-biz-attribute.change
ca.dealmoon.event.user-coupon.add
ca.dealmoon.event.user-info.cancel
ca.dealmoon.event.user-info.update
ca.dealmoon.event.user.biz-attribute.change
ca.dealmoon.event.user.follow
ca.dealmoon.event.user.login
ca.dealmoon.event.userdish.change
ca.dealmoon.event.voucher.about.to.expire
ca.dealmoon.event.voucher.auto.expire
ca.dealmoon.event.voucher.gift
ca.disclosure.ranking
ca.editor.work
ca.event.click
ca.hot_deal.activity_leadin_click
ca.hot_deal.clickRank_leadin_click
ca.hot_deal.comment_list_view
ca.hot_deal.deal_ad_click
ca.hot_deal.deal_ad_request
ca.hot_deal.deal_buy
ca.hot_deal.deal_click
ca.hot_deal.deal_comment
ca.hot_deal.deal_fav
ca.hot_deal.deal_leadin_click
ca.hot_deal.deal_share
ca.hot_deal.deal_view
ca.hot_deal.exchange_leadin_click
ca.hot_deal.groupBuy_leadin_click
ca.hot_deal.guide_leadin_click
ca.hot_deal.home_view
ca.hot_deal.hotSp_leadin_click
ca.hot_deal.hot_push_reading_leadin
ca.hot_deal.localBiz_leadin_click
ca.hot_deal.localEvent_leadin_click
ca.hot_deal.local_ad_click
ca.hot_deal.local_ad_request
ca.hot_deal.local_leadin_click
ca.hot_deal.local_view
ca.hot_deal.post_leadin_click
ca.hot_deal.publictest_leadin_click
ca.hot_deal.read
ca.hot_deal.spSubjectDetail_leadin_click
ca.hot_deal.subject_leadin_click
ca.impression
ca.link.convertor
ca.metric.event
ca.metric.view
ca.msg_center.msg_click
ca.public_test.behavior
ca.public_test.click
ca.public_test.view
ca.search.deal
ca.search_analysis.search_event
ca.search_analysis.sp_search_event
ca.sp.click
ca.sp.event
ca.sp.view
ca.ugc.event
ca.ugc.page_view
ca.ugc.ugc_click
ca.ugc.ugc_comment
ca.ugc.ugc_fav
ca.ugc.ugc_like
ca.ugc.ugc_share
ca.ugc.ugc_view
ca.ugc_album.view
ca.ugc_banner.click
ca.ugc_banner.view
ca.user.behavior
ca.user.entity
ca.user.score_log
ca.user.ugc_publish
cn.dealmoon.event.image.preheat
cn.dealmoon.event.resource.transport
cn.impression
common.dealmoon.event.write-cn-db-failed.retry
de.app.active
de.app.event
de.business.event.sp
de.deal.event
de.deal.impression.statistics
de.dealmoon.event.aladdin.data.pull
de.dealmoon.event.album.change
de.dealmoon.event.api-lottery
de.dealmoon.event.at.user
de.dealmoon.event.biz-module.update
de.dealmoon.event.business.dish.tag.changed
de.dealmoon.event.cart.sync
de.dealmoon.event.comment-num.update
de.dealmoon.event.comment.create
de.dealmoon.event.comment.delete
de.dealmoon.event.comment.update
de.dealmoon.event.complimentary.voucher
de.dealmoon.event.deal.update
de.dealmoon.event.disclosure.update
de.dealmoon.event.entity.add
de.dealmoon.event.es-command
de.dealmoon.event.favorite.change
de.dealmoon.event.guide.change
de.dealmoon.event.image.preheat
de.dealmoon.event.like.change
de.dealmoon.event.local-channel-setting.update
de.dealmoon.event.local-common-setting.update
de.dealmoon.event.local.business.change
de.dealmoon.event.local.businessDish.rewardRules.flushAll
de.dealmoon.event.local.category.changed
de.dealmoon.event.local.city.changed
de.dealmoon.event.local.county.changed
de.dealmoon.event.medal.approval
de.dealmoon.event.order.change
de.dealmoon.event.order.goods.verified
de.dealmoon.event.order.paid
de.dealmoon.event.order.refund
de.dealmoon.event.post.change
de.dealmoon.event.public-test.update
de.dealmoon.event.resource.transport
de.dealmoon.event.scheduled_task
de.dealmoon.event.share.change
de.dealmoon.event.source-city-relation.change
de.dealmoon.event.sp.update
de.dealmoon.event.submitted.global
de.dealmoon.event.ugc.elite
de.dealmoon.event.user-biz-attribute.change
de.dealmoon.event.user-coupon.add
de.dealmoon.event.user-info.cancel
de.dealmoon.event.user-info.update
de.dealmoon.event.user.biz-attribute.change
de.dealmoon.event.user.follow
de.dealmoon.event.user.login
de.dealmoon.event.userdish.change
de.dealmoon.event.voucher.about.to.expire
de.dealmoon.event.voucher.auto.expire
de.dealmoon.event.voucher.gift
de.disclosure.ranking
de.editor.work
de.event.click
de.hot_deal.activity_leadin_click
de.hot_deal.clickRank_leadin_click
de.hot_deal.comment_list_view
de.hot_deal.deal_ad_click
de.hot_deal.deal_ad_request
de.hot_deal.deal_buy
de.hot_deal.deal_click
de.hot_deal.deal_comment
de.hot_deal.deal_fav
de.hot_deal.deal_leadin_click
de.hot_deal.deal_share
de.hot_deal.deal_view
de.hot_deal.exchange_leadin_click
de.hot_deal.groupBuy_leadin_click
de.hot_deal.guide_leadin_click
de.hot_deal.home_view
de.hot_deal.hotSp_leadin_click
de.hot_deal.hot_push_reading_leadin
de.hot_deal.localBiz_leadin_click
de.hot_deal.localEvent_leadin_click
de.hot_deal.local_ad_click
de.hot_deal.local_ad_request
de.hot_deal.local_leadin_click
de.hot_deal.post_leadin_click
de.hot_deal.publictest_leadin_click
de.hot_deal.read
de.hot_deal.spSubjectDetail_leadin_click
de.hot_deal.subject_leadin_click
de.impression
de.link.convertor
de.metric.event
de.metric.view
de.msg_center.msg_click
de.public_test.applied
de.public_test.behavior
de.public_test.click
de.public_test.share
de.public_test.view
de.search.deal
de.search_analysis.search_event
de.search_analysis.sp_search_event
de.sp.click
de.sp.view
de.ugc.event
de.ugc.page_view
de.ugc.ugc_click
de.ugc.ugc_comment
de.ugc.ugc_fav
de.ugc.ugc_like
de.ugc.ugc_share
de.ugc.ugc_view
de.ugc_album.view
de.ugc_banner.click
de.ugc_banner.view
de.user.behavior
de.user.entity
de.user.score_log
de.user.ugc_publish
dealmoon.event.user.update
fr.app.active
fr.app.event
fr.app.view
fr.business.event.sp
fr.deal.event
fr.deal.impression.statistics
fr.dealmoon.event.album.change
fr.dealmoon.event.api-lottery
fr.dealmoon.event.at.user
fr.dealmoon.event.cart.sync
fr.dealmoon.event.comment-num.update
fr.dealmoon.event.comment.create
fr.dealmoon.event.comment.update
fr.dealmoon.event.deal.update
fr.dealmoon.event.disclosure.update
fr.dealmoon.event.entity.add
fr.dealmoon.event.es-command
fr.dealmoon.event.favorite.change
fr.dealmoon.event.guide.change
fr.dealmoon.event.image.preheat
fr.dealmoon.event.like.change
fr.dealmoon.event.local.business.change
fr.dealmoon.event.medal.approval
fr.dealmoon.event.order.change
fr.dealmoon.event.order.paid
fr.dealmoon.event.post.change
fr.dealmoon.event.resource.transport
fr.dealmoon.event.scheduled_task
fr.dealmoon.event.share.change
fr.dealmoon.event.sp.update
fr.dealmoon.event.submitted.global
fr.dealmoon.event.ugc.elite
fr.dealmoon.event.user-biz-attribute.change
fr.dealmoon.event.user-coupon.add
fr.dealmoon.event.user-info.cancel
fr.dealmoon.event.user-info.update
fr.dealmoon.event.user.biz-attribute.change
fr.dealmoon.event.user.follow
fr.dealmoon.event.user.login
fr.dealmoon.event.userdish.change
fr.dealmoon.event.voucher.gift
fr.disclosure.ranking
fr.editor.work
fr.event.click
fr.hot_deal.activity_leadin_click
fr.hot_deal.clickRank_leadin_click
fr.hot_deal.comment_list_view
fr.hot_deal.deal_ad_click
fr.hot_deal.deal_ad_request
fr.hot_deal.deal_buy
fr.hot_deal.deal_click
fr.hot_deal.deal_comment
fr.hot_deal.deal_fav
fr.hot_deal.deal_leadin_click
fr.hot_deal.deal_share
fr.hot_deal.deal_view
fr.hot_deal.exchange_leadin_click
fr.hot_deal.groupBuy_leadin_click
fr.hot_deal.guide_leadin_click
fr.hot_deal.home_view
fr.hot_deal.hotSp_leadin_click
fr.hot_deal.hot_push_reading_leadin
fr.hot_deal.localBiz_leadin_click
fr.hot_deal.localEvent_leadin_click
fr.hot_deal.local_ad_click
fr.hot_deal.local_ad_request
fr.hot_deal.local_leadin_click
fr.hot_deal.post_leadin_click
fr.hot_deal.publictest_leadin_click
fr.hot_deal.read
fr.hot_deal.spSubjectDetail_leadin_click
fr.hot_deal.subject_leadin_click
fr.impression
fr.link.convertor
fr.metric.event
fr.metric.view
fr.msg_center.msg_click
fr.public_test.applied
fr.public_test.behavior
fr.public_test.click
fr.public_test.share
fr.public_test.view
fr.search.deal
fr.search_analysis.search_event
fr.search_analysis.sp_search_event
fr.sp.click
fr.sp.event
fr.sp.view
fr.ugc.event
fr.ugc.page_view
fr.ugc.ugc_click
fr.ugc.ugc_comment
fr.ugc.ugc_fav
fr.ugc.ugc_like
fr.ugc.ugc_share
fr.ugc.ugc_view
fr.ugc_album.view
fr.ugc_banner.click
fr.ugc_banner.view
fr.user.behavior
fr.user.entity
fr.user.score_log
fr.user.ugc_publish
hot_deal.deal_click
hot_deal.deal_share
hot_deal.deal_view
image-preheat
msg-center-service-wechat-record-formId
msg-center-service-wechat-send-msg
uk.app.active
uk.app.event
uk.app.view
uk.business.event.sp
uk.deal.event
uk.deal.impression.statistics
uk.dealmoon.event.aladdin.data.pull
uk.dealmoon.event.album.change
uk.dealmoon.event.api-lottery
uk.dealmoon.event.at.user
uk.dealmoon.event.biz-module.update
uk.dealmoon.event.business.dish.tag.changed
uk.dealmoon.event.cart.sync
uk.dealmoon.event.comment-num.update
uk.dealmoon.event.comment.create
uk.dealmoon.event.comment.delete
uk.dealmoon.event.comment.update
uk.dealmoon.event.complimentary.voucher
uk.dealmoon.event.deal.update
uk.dealmoon.event.disclosure.update
uk.dealmoon.event.entity.add
uk.dealmoon.event.es-command
uk.dealmoon.event.favorite.change
uk.dealmoon.event.guide.change
uk.dealmoon.event.image.preheat
uk.dealmoon.event.like.change
uk.dealmoon.event.local-channel-setting.update
uk.dealmoon.event.local-common-setting.update
uk.dealmoon.event.local.business.change
uk.dealmoon.event.local.businessDish.rewardRules.flushAll
uk.dealmoon.event.local.category.changed
uk.dealmoon.event.local.city.changed
uk.dealmoon.event.local.county.changed
uk.dealmoon.event.medal.approval
uk.dealmoon.event.order.change
uk.dealmoon.event.order.goods.verified
uk.dealmoon.event.order.paid
uk.dealmoon.event.order.refund
uk.dealmoon.event.post.change
uk.dealmoon.event.public-test.update
uk.dealmoon.event.resource.transport
uk.dealmoon.event.scheduled_task
uk.dealmoon.event.share.change
uk.dealmoon.event.source-city-relation.change
uk.dealmoon.event.sp.update
uk.dealmoon.event.submitted.global
uk.dealmoon.event.ugc.elite
uk.dealmoon.event.user-biz-attribute.change
uk.dealmoon.event.user-coupon.add
uk.dealmoon.event.user-info.cancel
uk.dealmoon.event.user-info.update
uk.dealmoon.event.user.biz-attribute.change
uk.dealmoon.event.user.follow
uk.dealmoon.event.user.login
uk.dealmoon.event.userdish.change
uk.dealmoon.event.voucher.about.to.expire
uk.dealmoon.event.voucher.auto.expire
uk.dealmoon.event.voucher.gift
uk.disclosure.ranking
uk.editor.work
uk.event.click
uk.hot_deal.activity_leadin_click
uk.hot_deal.clickRank_leadin_click
uk.hot_deal.comment_list_view
uk.hot_deal.deal_ad_click
uk.hot_deal.deal_ad_request
uk.hot_deal.deal_buy
uk.hot_deal.deal_click
uk.hot_deal.deal_comment
uk.hot_deal.deal_fav
uk.hot_deal.deal_leadin_click
uk.hot_deal.deal_share
uk.hot_deal.deal_view
uk.hot_deal.event
uk.hot_deal.exchange_leadin_click
uk.hot_deal.groupBuy_leadin_click
uk.hot_deal.guide_leadin_click
uk.hot_deal.home_view
uk.hot_deal.hotSp_leadin_click
uk.hot_deal.hot_push_reading_leadin
uk.hot_deal.localBiz_leadin_click
uk.hot_deal.localEvent_leadin_click
uk.hot_deal.local_ad_click
uk.hot_deal.local_ad_request
uk.hot_deal.local_leadin_click
uk.hot_deal.post_leadin_click
uk.hot_deal.publictest_leadin_click
uk.hot_deal.read
uk.hot_deal.spSubjectDetail_leadin_click
uk.hot_deal.subject_leadin_click
uk.impression
uk.link.convertor
uk.metric.event
uk.metric.view
uk.msg_center.msg_click
uk.public_test.applied
uk.public_test.behavior
uk.public_test.click
uk.public_test.share
uk.public_test.view
uk.search.deal
uk.search_analysis.search_event
uk.search_analysis.sp_search_event
uk.sp.click
uk.sp.event
uk.sp.view
uk.ugc.event
uk.ugc.page_view
uk.ugc.ugc_click
uk.ugc.ugc_comment
uk.ugc.ugc_fav
uk.ugc.ugc_like
uk.ugc.ugc_share
uk.ugc.ugc_view
uk.ugc_album.view
uk.ugc_banner.click
uk.ugc_banner.view
uk.user.behavior
uk.user.entity
uk.user.score_log
uk.user.ugc_publish
undefinedhot_deal.deal_view
us.business.event.sp
us.dealmoon.event.ad.change
us.dealmoon.event.aladdin.data.pull
us.dealmoon.event.album.change
us.dealmoon.event.api-lottery
us.dealmoon.event.at.user
us.dealmoon.event.biz-module.update
us.dealmoon.event.biz.sp.event
us.dealmoon.event.business.dish.tag.changed
us.dealmoon.event.cart.sync
us.dealmoon.event.comment-num.update
us.dealmoon.event.comment.create
us.dealmoon.event.comment.delete
us.dealmoon.event.comment.update
us.dealmoon.event.complimentary.voucher
us.dealmoon.event.deal.update
us.dealmoon.event.disclosure.update
us.dealmoon.event.entity.add
us.dealmoon.event.es-command
us.dealmoon.event.favorite.change
us.dealmoon.event.goods.group.cancel
us.dealmoon.event.guide.change
us.dealmoon.event.image.preheat
us.dealmoon.event.like.change
us.dealmoon.event.local-channel-setting.update
us.dealmoon.event.local-common-setting.update
us.dealmoon.event.local.business.change
us.dealmoon.event.local.businessDish.rewardRules.flushAll
us.dealmoon.event.local.category.changed
us.dealmoon.event.local.city.changed
us.dealmoon.event.local.county.changed
us.dealmoon.event.medal.approval
us.dealmoon.event.order.change
us.dealmoon.event.order.goods.verified
us.dealmoon.event.order.paid
us.dealmoon.event.order.refund
us.dealmoon.event.post.change
us.dealmoon.event.public-test.update
us.dealmoon.event.public-test_star.update
us.dealmoon.event.rec.config.change
us.dealmoon.event.recommend.recon.doc.update
us.dealmoon.event.resource.transport
us.dealmoon.event.scheduled_task
us.dealmoon.event.share.change
us.dealmoon.event.source-city-relation.change
us.dealmoon.event.sp.update
us.dealmoon.event.submitted.global
us.dealmoon.event.ugc.elite
us.dealmoon.event.user-biz-attribute.change
us.dealmoon.event.user-coupon.add
us.dealmoon.event.user-info.cancel
us.dealmoon.event.user-info.update
us.dealmoon.event.user.biz-attribute.change
us.dealmoon.event.user.buy.goods.balance.update
us.dealmoon.event.user.follow
us.dealmoon.event.user.login
us.dealmoon.event.userdish.change
us.dealmoon.event.voucher.about.to.expire
us.dealmoon.event.voucher.auto.expire
us.dealmoon.event.voucher.gift
us.impression
user.punch.card.statistics
"""

# # 统计以biz或者us开头的topic
# us_logs = []
# for x in s.split('\n'):
# 	if 'dealmoon.event' in x: continue
#
# 	splits = x.split('.')
# 	site = splits[0].lower()
# 	if site == 'biz':
# 		us_logs.append(x[4:])
# 	elif site == 'us':
# 		us_logs.append(x[3:])
#
# print(json.dumps(us_logs))
#
# # 没有以站点名开头，或者是有站点名，但美国站却没有的埋点
# no_site_logs, other_logs = [], []
# sites = ['de', 'fr', 'au', 'uk', 'ca', 'biz', 'us', 'cn']
# for x in s.split('\n'):
#
# 	if 'dealmoon.event' in x: continue
#
# 	site = x.split('.')[0].lower()
#
# 	if site not in sites:
# 		no_site_logs.append(x)
# 		continue
#
# 	if x[len(site) + 1:] not in us_logs:
# 		other_logs.append(x)
# print(json.dumps(other_logs))
# print(json.dumps(no_site_logs))


lst = []
for x in s.split("\n"):
	x = x.strip()
	if not x: continue
	if "dealmoon.event" in x: continue
	lst.append(x)
print(json.dumps(lst))
